/*Filtrando dados com
WHERE e LIKE*/
SELECT  NOME
       ,TELEFONE
FROM CLIENTE; /*FILTRANDO*/

SELECT  NOME
       ,SEXO
FROM CLIENTE
WHERE SEXO='M';

SELECT  NOME
       ,ENDERECO
FROM CLIENTE
WHERE SEXO='F';

SELECT  NOME
       ,SEXO
FROM CLIENTE
WHERE ENDERECO = 'RJ';
/*UTILIZANDO LIKE*/
SELECT  NOME
       ,SEXO
FROM CLIENTE
WHERE ENDERECO LIKE 'RIO'; /*ERRADO*/ /* CARACTER CORINGA % */

SELECT  NOME
       ,SEXO
FROM CLIENTE
WHERE ENDERECO LIKE '%RIO';

SELECT  NOME
       ,SEXO
FROM CLIENTE
WHERE ENDERECO LIKE '%ESTACIO%';