/* O COMANDO SELECT*/
SELECT NOW();

SELECT 'FELIPE MAFRA';

SELECT 'BANCO DE DADOS';

SELECT NOME, SEXO, EMAIL
FROM CLIENTE; 

/* ALIAS DE COLUNAS */
SELECT 'FELIPE MAFRA' AS PROFESSOR; 


/*APENAS PARA FINS ACADEMICOS*/
SELECT * FROM CLIENTE;