/* COUNT (*), GROUP BY, PERFORMANCE COM OPERADORES LÓGICOS */ /* CONTANDO OS REGISTROS DE UMA TABELA */
SELECT  COUNT(*)
FROM CLIENTE;

SELECT  COUNT(*) AS "QUANTIDADE"
FROM CLIENTE;

/* OPERADOR GROUP BY */

SELECT SEXO, COUNT(*) AS "QUANTIDADE"
FROM CLIENTE
GROUP BY SEXO;


/* PERFORMANCE EM OPERADORES LÓGICOS */

/* 1 MILHÃO DE REGISTROS

PARA CONTAR
SELECT COUNT(*) FROM CLIENTE;

SELECT SEXO, COUNT(*) FROM CLIENTE
GROUP BY SEXO;

SELECT CIDADE, COUNT(*) FROM CLIENTE
GROUP BY CIDADE;

CONDICAO
SEXO = F
CIDADE = RIO DE JANEIRO

SITUACAO - TRATANDO COM OU / OR
% MULHERES = SEXO = F
% MORA NO RIO DE JANEIRO

SELECT NOME, SEXO, ENDERECO
FROM CLIENTE
WHERE SEXO = 'F'
OR CIDADE = 'RIO DE JANEIRO';

SITUACAO - TRATANDO COM E / AND
70% MULHERES = SEXO = F
30% MORA NO RIO DE JANEIRO

SELECT NOME, SEXO, ENDERECO
FROM CLIENTE
OR CIDADE = 'RIO DE JANEIRO'
WHERE SEXO = 'F';


PARA OU - PORCENTAGEM MAIOR VERDADEIRA NA PRIMEIRA CONDIÇÃO

PARA AND - PROCENTAGEM MENOR VERDADEIRA NA PRIMEIRA CONDIÇÃO
*/