/* A11 - OPERADORES LÓGICOS */ /* OR - OU */
SELECT  NOME
       ,EMAIL
FROM CLIENTE
WHERE SEXO = 'M' OR ENDERECO LIKE '%RIO';

SELECT  NOME
       ,EMAIL
FROM CLIENTE
WHERE SEXO = 'F' OR ENDERECO LIKE '%ESTACIO%'; /*
AND - E */
SELECT  NOME
       ,EMAIL
FROM CLIENTE
WHERE SEXO = 'M'
AND ENDERECO LIKE '%RIO';

SELECT  NOME
       ,EMAIL
FROM CLIENTE
WHERE SEXO = 'F'
AND ENDERECO LIKE '%ESTACIO%';